language: node_js
services:
  - mongodb
node_js:
  - "4"
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
  firefox: "latest"
before_cache:
  - rm -rf $HOME/build/openmarketplace/openmarketplace/.meteor/local/log
  - rm -rf $HOME/build/openmarketplace/openmarketplace/.meteor/local/run
  - rm -rf $HOME/build/openmarketplace/openmarketplace/.meteor/local/db
before_install:
  - if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi
before_script:
  - "export PATH=$HOME/.meteor:$PATH"
notifications:
  slack: open-marketplace:gyLmoLZbhRDl9k6UMRvWMmvC
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/223aa9c20089a22f388b
    on_success: always
    on_failure: always
    on_start: never
